### ISSUE TITLE
Поднять негасимый инстанс

### ISSUE THREAD

**Issue by SemyonMakhaev** [comsq2017/where-to-go#4]
Инстансы в now по умолчанию автоматически замораживаются через некоторое время отсутствия активности. Это поведение можно отключить, указав минимальное количество инстансов:

```bash
> now scale wtg.now.sh 1
```

https://zeit.co/blog/scale

**Comment by dimastark** [comment]
Уже настроено ведь.

**Comment by SemyonMakhaev** [comment]
Я сегодня утром загружал его минуты 2
😱

**Comment by dimastark** [comment]
Скорее всего утром он вообще не загружался) Почему то при автодеплое alias не сработал. На wtg.now.sh скорее всего пусто было.
